version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - 2181:2181
    logging: { driver: none }

  kafka-broker:
    image: confluentinc/cp-kafka:7.2.3
    ports:
    - 9092:9092
    - 9010:9010
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENERS=PUBLIC://0.0.0.0:9092,INTERNAL://0.0.0.0:19092
    - KAFKA_ADVERTISED_LISTENERS=PUBLIC://localhost:9092,INTERNAL://kafka-broker:19092
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PUBLIC:PLAINTEXT,INTERNAL:PLAINTEXT
    - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    - KAFKA_NUM_PARTITIONS=2
    - KAFKA_DEFAULT_REPLICATION_FACTOR=1
    - KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=10
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    - KAFKA_DELETE_TOPIC_ENABLE=true
    - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
    - KAFKA_LOG4J_ROOT_LOGLEVEL=INFO
    - KAKFA_JMX_HOST=localhost
    - KAFKA_JMX_PORT=9010
    depends_on: [zookeeper]
    logging: { driver: none }

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.3
    hostname: schema-registry
    ports:
    - 8000:8000
    - 9011:9011
    environment:
    - SCHEMA_REGISTRY_HOST_NAME=schema-registry
    - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8000
    - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka-broker:19092
    - SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR=1
    - SCHEMA_REGISTRY_KAFKASTORE_TIMEOUT_MS=15000
    - SCHEMA_REGISTRY_JMX_HOST=localhost
    - SCHEMA_REGISTRY_JMX_PORT=9011
    depends_on: [zookeeper, kafka-broker]
    logging: { driver: none }
